version: "3.9"
services:
  wordpress:
    image: wordpress:fpm-alpine
    volumes:
      - wordpress_data_bitnami:/var/www/html
    networks:
      - proxy
      - network_public
    environment:
      - WORDPRESS_DB_NAME=bitnami_wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_PORT=3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Ken172ji
      - WP_REDIS_HOST=redis
      - WP_REDIS_DATABASE=6
      - VIRTUAL_HOST=emersontakada.co.uk
      - WP_LOCALE=pt_BR
      # - WORDPRESS_CONFIG_EXTRA=define('FS_METHOD', 'direct');
      - WORDPRESS_DEBUG=1

  nginx:
    image: nginx:alpine
    ports:
      - 8095:80
    volumes:
      - wordpress_data_bitnami:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nginx.rule=Host(`emersontakada.co.uk`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=le"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  wordpress_data_bitnami:
    external: true

networks:
  network_public:
    external: true
  proxy:
    external: true
