version: '3.8'

services:
  nginx_web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nginx_data:/usr/share/nginx/html
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_web.rule=Host(`teste.emersontakada.co.uk`)"
      - "traefik.http.routers.nginx_web.entrypoints=websecure"
      - "traefik.http.routers.nginx_web.tls.certresolver=le"
      - "traefik.http.services.nginx_web.loadbalancer.server.port=80"
      - "traefik.http.services.nginx_web.loadbalancer.sticky=true"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  nginx_data:
