version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_test
    volumes:
      - ./system/index.html:/usr/share/nginx/html/index.html:ro
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`emersontakada.co.uk`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=le"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.sticky=true"
    networks:
      - proxy

networks:
  proxy:
    external: true