version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf  # Arquivo nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d  # Diretório conf.d com my_site.conf
      - ./system:/var/www/html:ro  # Diretório para os arquivos do site
    ports:
      - "8080:80"
    networks:
      - network_public
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
          condition: on-failure
      placement:
          constraints:
            - node.role == manager
networks:
  network_public:
    external: true