version: "3.9"
services:
  wordpress:
    image: wordpress:fpm-alpine
    volumes:
      - wordpress_data_bitnami:/var/www/html
    networks:
      - proxy
      - network_public
    environment:
      - WORDPRESS_DB_NAME=bitnami_wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_PORT=3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Ken172ji
      - WP_REDIS_HOST=redis
      - WP_REDIS_DATABASE=6
      - VIRTUAL_HOST=teste.emersontakada.co.uk
      - WP_LOCALE=pt_BR
      # - WORDPRESS_CONFIG_EXTRA=define('FS_METHOD', 'direct');
      - WORDPRESS_DEBUG=1

  nginx:
    image: nginx:alpine
    volumes:
      - wordpress_data_bitnami:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - network_public
    labels:
      # Configuração básica
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      
      # Router HTTPS
      - "traefik.http.routers.nginx-secure.rule=Host(`teste.emersontakada.co.uk`)"
      - "traefik.http.routers.nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-secure.tls.certresolver=le"
      - "traefik.http.routers.nginx-secure.service=nginx-service"
      
      # Service
      - "traefik.http.services.nginx-service.loadbalancer.server.port=80"
      - "traefik.http.services.nginx-service.loadbalancer.passHostHeader=true"
      
      # Middlewares
      - "traefik.http.middlewares.nginx-secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.nginx-secure-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nginx-secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nginx-secure-headers.headers.stsPreload=true"
      
      # Aplicar middlewares ao router
      - "traefik.http.routers.nginx-secure.middlewares=nginx-secure-headers"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  wordpress_data_bitnami:
    external: true

networks:
  network_public:
    external: true
  proxy:
    external: true
