version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: your_db_host
      WORDPRESS_DB_USER: your_db_user
      WORDPRESS_DB_PASSWORD: your_db_password
      WORDPRESS_DB_NAME: your_db_name
    ports:
      - "8080:80" 
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  wordpress_data:

networks:
  default:
    driver: overlay