version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./config/conf.d:/etc/nginx/conf.d:ro
      - ./system:/var/www/html:ro  # Changed this line
    ports:
      - "8080:80"
    networks:
      - network_public
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
        condition: on-failure

networks:
  network_public:
    external: true