version: "3.9"
services:
  wordpress:
    image: wordpress:fpm-alpine
    volumes:
      - wordpress_data_bitnami:/var/www/html
    networks:
      - proxy
      - network_public
    environment:
      - WORDPRESS_DB_NAME=bitnami_wordpress
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_PORT=3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=Ken172ji
      - WP_REDIS_HOST=redis
      - WP_REDIS_DATABASE=6
      - VIRTUAL_HOST=teste.emersontakada.co.uk
      - WP_LOCALE=pt_BR
      - WORDPRESS_CONFIG_EXTRA=define('FS_METHOD', 'direct');
      - WORDPRESS_DEBUG=1

  nginx:
    image: nginx:alpine
    volumes:
      - wordpress_data_bitnami:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Router
      - "traefik.http.routers.nginx-teste.rule=Host(`teste.emersontakada.co.uk`)"
      - "traefik.http.routers.nginx-teste.entrypoints=websecure"
      - "traefik.http.routers.nginx-teste.tls.certresolver=le"
      # Service
      - "traefik.http.services.nginx-teste.loadbalancer.server.port=80"
      - "traefik.http.services.nginx-teste.loadbalancer.passHostHeader=true"
      # Middlewares
      - "traefik.http.middlewares.nginx-teste-compress.compress=true"
      - "traefik.http.middlewares.nginx-teste-headers.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.nginx-teste-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nginx-teste-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nginx-teste-headers.headers.stsSeconds=31536000"
      - "traefik.http.routers.nginx-teste.middlewares=nginx-teste-compress,nginx-teste-headers"  
    # labels:
    #   # Configuração básica
    #   - "traefik.enable=true"
      
    #   # Router para HTTPS
    #   - "traefik.http.routers.nginx.rule=Host(`teste.emersontakada.co.uk`)"
    #   - "traefik.http.routers.nginx.entrypoints=websecure"
    #   - "traefik.http.routers.nginx.tls.certresolver=le"
    #   - "traefik.http.routers.nginx.service=nginx-service"
      
    #   # Router para HTTP (redirecionamento)
    #   - "traefik.http.routers.nginx-http.rule=Host(`teste.emersontakada.co.uk`)"
    #   - "traefik.http.routers.nginx-http.entrypoints=web"
    #   - "traefik.http.routers.nginx-http.middlewares=redirect-to-https"
      
    #   # Middleware para redirecionamento HTTP -> HTTPS
    #   - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    #   - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      
    #   # Configuração do serviço
    #   - "traefik.http.services.nginx-service.loadbalancer.server.port=80"
    #   - "traefik.http.services.nginx-service.loadbalancer.passHostHeader=true"
      
    #   # Opcional: Middleware para compressão
    #   - "traefik.http.middlewares.compress.compress=true"
    #   - "traefik.http.routers.nginx.middlewares=compress"
      
    #   # Opcional: Headers de segurança
    #   - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
    #   - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
    #   - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  wordpress_data_bitnami:
    external: true

networks:
  network_public:
    external: true
  proxy:
    external: true
