version: '3.9'

services:
  nginx:
    image: nginx:latest
    # container_name: nginx_test
    ports:
      - "8088:80"
    volumes:
      - ./system:/usr/share/nginx/html:ro
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`emersontakada.co.uk`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=le"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.sticky=true"
    networks:
      - proxy
networks:
  proxy:
    external: true